brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown
      learn-filename: skitcb.aiml

    # Nodes
    nodes:
      pattern_nodes: $BOT_ROOT\config\pattern_nodes.conf
      template_nodes: $BOT_ROOT\config\template_nodes.conf

    # Binary
    binaries:
      save_binary: true
      load_binary: true
      binary_filename: $BOT_ROOT\skitcb.brain
      load_aiml_on_binary_fail: true

    # Braintree
    braintree:
      file: $BOT_ROOT\temp\braintree.xml
      content: xml

    files:
        aiml:
            files: $BOT_ROOT\aiml
            extension: .aiml
            directories: true
            conversation:
              file: $BOT_ROOT\temp\skitcb-conversation.csv
              format: csv
              delete_on_start: true
              empty_on_start: true
            errors: 
              file: $BOT_ROOT\temp\skitcb_errors.txt
              format: txt
              delete_on_start: true
              empty_on_start: true
            duplicates: 
              file: $BOT_ROOT\temp\skitcb_duplicates.txt
              format: txt
              delete_on_start: true
              empty_on_start: true

        sets:
            files: $BOT_ROOT\sets
            extension: .txt
            directories: false
        maps:
            files: $BOT_ROOT\maps
            extension: .txt
            directories: false
        denormal: $BOT_ROOT\config\denormal.txt
        normal: $BOT_ROOT\config\normal.txt
        gender: $BOT_ROOT\config\gender.txt
        person: $BOT_ROOT\config\person.txt
        person2: $BOT_ROOT\config\person2.txt
        properties: $BOT_ROOT\config\properties.txt
        preprocessors: $BOT_ROOT\config\preprocessors.conf
        postprocessors: $BOT_ROOT\config\postprocessors.conf
        regex_templates: $BOT_ROOT\config\regex-templates.txt
        variables: $BOT_ROOT\config\default-variables.txt


    services:
        REST:
            classname: programy.services.rest.GenericRESTService
            method: GET
            host: 0.0.0.0
            port: 5000
            url: /api/v1.0/ask
        

bot:
    prompt: ">>>"
    initial_question: Hi, how can I help you today?
    default_response: Sorry, I don't have an answer for that!
    empty_string: YEMPTY
    exit_response: So long!
    override_properties: true
    max_recursion: 100

    conversations:
      type: file
      config_name: file_storage
      empty_on_start: true

    file_storage:
      dir: $BOT_ROOT\temp

rest:
  host: 0.0.0.0
  port: 5000
  debug: false

webchat:
  host: 0.0.0.0
  port: 5000
  debug: false
