bot:
    prompt: ">>>"

    initial_question: Hi, how can I help you today?
    #default_response: Would you like to do a search for it!
    #default_response_srai: YEMPTY
    #empty_string: YEMPTY
    exit_response: So long!

    override_properties: true

    max_question_recursion: 100000
    max_question_timeout: 600
    max_search_depth: 1000
    max_search_timeout: 600

    conversations:
      type: file
      config_name: file_storage
      empty_on_start: true

    file_storage:
      dir: $BOT_ROOT/conversations

brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown
      learn-filename: skitcb-learnf.aiml

    # Nodes
    nodes:
      pattern_nodes: $BOT_ROOT/config/pattern_nodes.conf
      template_nodes: $BOT_ROOT/config/template_nodes.conf

    # Binary
    binaries:
      save_binary: true
      load_binary: false
      binary_filename: /tmp/skitchatbot.brain
      load_aiml_on_binary_fail: true


    # Braintree
    braintree:
      file: /tmp/braintree.xml
      content: xml

    files:
        aiml:
            files: $BOT_ROOT/aiml
            extension: .aiml
            directories: true
            conversation:
              file: /tmp/skitcb-conversation.csv
              format: csv

        sets:
            files: $BOT_ROOT/sets
            extension: .txt
            directories: false
        maps:
            files: $BOT_ROOT/maps
            extension: .txt
            directories: false
        denormal: $BOT_ROOT/config/denormal.txt
        normal: $BOT_ROOT/config/normal.txt
        gender: $BOT_ROOT/config/gender.txt
        person: $BOT_ROOT/config/person.txt
        person2: $BOT_ROOT/config/person2.txt
        properties: $BOT_ROOT/config/properties.txt
        preprocessors: $BOT_ROOT/config/preprocessors.conf
        postprocessors: $BOT_ROOT/config/postprocessors.conf
        regex_templates: $BOT_ROOT/config/regex-templates.txt
        variables: $BOT_ROOT/config/default-variables.txt

    services:
        REST:
            classname: programy.services.programy.ProgramyRESTService
            method: GET
            host: 0.0.0.0
            port: 8989
            url: /api/v1.0/ask
        Wikipedia:
            classname: programy.services.wikipediaservice.WikipediaService
        DuckDuckGo:
            classname: programy.services.duckduckgo.DuckDuckGoService
            url: http://api.duckduckgo.com


rest:
  host: 0.0.0.0
  port: 8989
  debug: false

webchat:
  host: 0.0.0.0
  port: 8080
  debug: false
